# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Instagram Followers Extractor

on:
  workflow_dispatch: # enable manual run
    inputs:
      git-ref:
        description: Git Ref (Optional)
        required: false
  schedule:
    - cron: '0 0 * * *' #  Runs at 00:00 UTC every day. 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install instaloader
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Get Followers for given user
      run: |
        python main.py
      env:
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
    
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"     
    
    - name: Get Number of Followers 
      id: get_number_of_followers
      run: echo "::set-output name=FOLLOWERS::$(echo "$(cat ./inst_followers-*.csv | wc -l) - 1" | bc)" 
    
    - name: Empty commit push
      run: |
        git config --global user.email "robotcuk@randommail.com"
        git config --global user.name "robotcuk"
        git commit --allow-empty -m "Followers extracted: ${{ steps.date.outputs.date }}"
        git tag -a ${{ steps.date.outputs.date }} -m "${{ steps.get_number_of_followers.outputs.FOLLOWERS }} followers on ${{ steps.date.outputs.date }}"
        git push origin ${{ steps.date.outputs.date }}
        git push origin -f master
      env:
        GITHUB_TOKEN: ${{ secrets.ROBOTCUK }}
   
      
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.date.outputs.date }} 
        release_name: ${{ steps.get_number_of_followers.outputs.FOLLOWERS }} Followers information saved at ${{ steps.date.outputs.date }}
        draft: false
        prerelease: false
    
    - name: Upload Release Assets
      uses: shogo82148/actions-upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./*.csv


     
